### ISSUE TITLE
Failing `minetest.get_inventory` call results in nil error

### ISSUE THREAD

**Issue by Alatarius** [minetest-mods/castle_lighting#6]
Every time I have used this mod my game will kill itself with this error.
```lua
AsyncErr: Lua: Runtime error from mod 'castle_lighting' in callback node_on_timer(): D:\Games\Minetest\bin\..\mods\castle_lighting/brasier.lua:41: attempt to index local 'inv' (a nil value)
stack traceback:
	D:\Games\Minetest\bin\..\mods\castle_lighting/brasier.lua:41: in function <D:\Games\Minetest\bin\..\mods\castle_lighting/brasier.lua:33>
```
[edit] Server won't even load with this mod installed: (error given)
```lua
AsyncErr: Lua: Runtime error from mod 'castle_lighting' in callback node_on_timer(): D:\Games\Minetest\bin\..\mods\castle_lighting/brasier.lua:41: attempt to index local 'inv' (a nil value)
stack traceback:
	D:\Games\Minetest\bin\..\mods\castle_lighting/brasier.lua:41: in function <D:\Games\Minetest\bin\..\mods\castle_lighting/brasier.lua:33>
```

**Comment by SmallJoker** [comment]
Would you please be so nice to reproduce this issue in a new world and share all world files by uploading an archive to your preferred host? I would like to investigate this further.

If that is too much effort, please change the following code:
https://github.com/minetest-mods/castle_lighting/blob/d520cd4cf3498fa37b9e67a0e398b205af0f10b6/brasier.lua#L42-L44
to this:
```Lua
	local inv = minetest.get_inventory({type="node", pos=pos})
	if not inv then
		minetest.log("error", "Ran node timer on node without inventory: " .. minetest.get_node(pos).name)
		return
	end
	local item = inv:get_stack("fuel", 1)
```

and share the newly generated errors. I suspect there is a mod that used `minetest.swap_node` or VManip that does not clear the node timer.
